# Generated by Django 5.0.6 on 2024-06-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
    ]
